name: Tests

on:
  push:
    branches:
      - main  

jobs:
  build:

    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'  

    - name: Test 2.1 string utility project
      working-directory: ./string_utility_project  
      run: mvn clean test -q

    - name: Test 2.2 bowling game project
      working-directory: ./bowling_game_project  
      run: mvn clean test -q

